services:
  yolov26:
    build: .
    container_name: yunding360_yolortsp
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TZ=Asia/Shanghai
    volumes:
      - ./video.mp4:/app/video.mp4:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3G
